name = "packgod"
main = "./packgod.js"
compatibility_date = "2025-06-10"
compatibility_flags = [
  "nodejs_compat"
]

[vars]
PUBLIC_KEY = "b84486d2790db08eb30f9dd759581ac2f4e9e687c57b2f60d0a6606d95f98210"

[observability.logs]
enabled = true